### ISSUE TITLE
TPot for kubernetes

### ISSUE THREAD

**Issue by boddumanohar** [telekom-security/tpotce#1163]
**Is your feature request related to a problem? Please describe.**
At the moment, Kubernetes based deployments are quite common, even in the academic areas. It would be great addition we could have Kubernetes based deployment setup so that tpot can also be used for container research area also. 

**Describe the solution you'd like**
Port the current infrasture to Kubernetes by comming up .yaml files

**Describe alternatives you've considered**

**Additional context**

**Comment by t3chn0m4g3** [comment]
Thank you for the feature request.
At the moment there are no immediate plans to adjust or port T-Pot to Kubernetes or other platforms for that matter.
The reason being a port would not allow for the same feature set currently offered since many features rely on the installation on a host and its services.
