### ISSUE TITLE
Tpot - UI Issue - 400 Bad Request

### ISSUE THREAD

**Issue by cvdsouza** [telekom-security/tpotce#1205]
Hi , 
After running an update using the ./update.sh , I'm getting this error : 
```
400 Bad Request
Request Header Or Cookie Too Large
nginx
```
Online articles say it is on the client side, but I've tried on multiple clients and still getting the error. Any suggestion on what the issue could be ? 

Interestingly the Cockpit UI works fine. It's just the TPOT UI on https://<your.ip>:64297 that is giving this error.

**Comment by t3chn0m4g3** [comment]
Can you shed more light on this? Did you upgrade from 20.x or have you been running 22.x all along?
Since the T-Pot UI is docker based with static content it is more likely it is an issue with the client (just checked on my end and it works just fine).
Have you tried opening with private mode enabled (just to see if it is cache related)?

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.

**Comment by cvdsouza** [comment]
Hi, 
Apologies for the delayed response. Yes the issue was resolved (I'm running the latest version of T-POT all along 22.x) : 
1. Clearing browser cache and DNS cache. 
2. The underlying issues had to do with Cloudflare ZTNA behind which the T-POT UI sits. It seems cloudflare is spitting out the 400 error. For now I've taken the UI out of ZTNA and it works fine.

**Comment by t3chn0m4g3** [comment]
Thank you for the valued feedback, this helps us and others!
