### ISSUE TITLE
Use install.sh to always fail to install

### ISSUE THREAD

**Issue by yunfengwangluo** [telekom-security/tpotce#1265]
### We recommend a fresh install according to the T-Pot Readme Post-Install method.

Aborting.

I install in Debian 11.6, no matter what I do, no matter whether I add tpot users or not This prompt will appear eventually. Installation failed

**Comment by t3chn0m4g3** [comment]
Cannot reproduce.

**Comment by krzotr** [comment]
I had a similar issue. I created a user `admin_tpot` and got **The user name "tpot" already exists.**

The problem is in `iso/installer/install.sh` file https://github.com/telekom-security/tpotce/blob/88ab453061e42188ae65e8fca783f0d4e81049e3/iso/installer/install.sh#L446

Lazy check, grep finds string `tpot` but not user `tpot`. Regexp should be `^tpot:`.
