### ISSUE TITLE
RHEL support

### ISSUE THREAD

**Issue by mattroot** [telekom-security/tpotce#1602]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add official support for Red Hat Enterprise Linux Server.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
I tend to use T-Pot in an environment where I am forced to run hive on a RHEL machine. Theoretically supporting it officially shouldn't be a big deal, as Alma and Rocky are already supported. It's just a matter of including it in playbooks.

**Comment by t3chn0m4g3** [comment]
@mattroot Red Hat does not even provide install images without registering first. Given all the obstacles with an official / paid subscription I also do not think it is a good fit for T-Pot which is fully committed to open source.
At this point I would not even accept a well hearted PR to support RHEL as I could not actively maintain it due to the lack of free (without registering) ISO downloads.
Sorry to disappoint and thanks for understanding.
