### ISSUE TITLE
Update Server IPs

### ISSUE THREAD

**Issue by an-schall** [telekom-security/tpotce#744]
For deploying T-POT in our environment, it is necessary to define all data flows of T-POT, including the ones toward the Internet for updating the framework.

Is there detailed overview which IP / hostnames (including ports) T-POT needs to connect to in order to function properly?

Thanks in advance.

**Comment by t3chn0m4g3** [comment]
There is no comprehensive documentation WRT to remote sites T-Pot needs access to. A good start is the [architecture overview](https://github.com/telekom-security/tpotce/blob/master/doc/architecture.png). However please be aware that some honeypots (i.e. Cowrie) need access to the internet in order to download appropriate payloads and there is no way to correctly document remote IPs alongside URLs since they change too often.

In the future please post questions in [Discussions](url) - Thanks :bowtie:

**Comment by an-schall** [comment]
Hi there,

sorry for posting in the wrong section. I tried to identify the endpoints t-pot talks to for receiving updates etc. by logging the outgoing traffic on the firewall. However, there is so much traffic to so many endpoints that it is really hard to identify which traffic belongs to the update processes. I have no idea how I could efficiently identify the actual endpoints.

Unfortunately, we have do provide such documentation at our organization since "ANY" rules at the firewalls are not allowed.

In general, wouldn't it be sufficient to allow only traffic to your github i.e. the traffic that is generated when running ./update.sh?

Thanks.

**Comment by drphr4ud** [comment]
It will be hard to run T-POT given the constraints you are working within. For one it needs to update debian packages from debian mirrors. If you need to document and seek permission for specific IP address egress you will find it difficult to manage.
