### ISSUE TITLE
Kibana Dashborad problems after fresh install

### ISSUE THREAD

**Issue by certrik** [telekom-security/tpotce#845]
Fresh install via 
```
git clone https://github.com/telekom-security/tpotce
cd tpotce/iso/installer/
./install.sh --type=user
```
getting ...
```
Fetching listing failed

The dashboard listing could not be fetched: getaddrinfo ENOTFOUND elasticsearch.
```
on Kibana Dashboard.
![grafik](https://user-images.githubusercontent.com/42176839/120081815-be5d3c80-c0bf-11eb-808a-465087d3950a.png)

**Comment by t3chn0m4g3** [comment]
Please provide more details. Cannot reproduce this.

**Comment by certrik** [comment]
Hi @t3chn0m4g3 ,
Happy to provide more details. Which logs do you need?

**Comment by t3chn0m4g3** [comment]
The ones you saw when you opened the issue.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.

**Comment by JakeFrom98** [comment]
I'm having the same exact issue. 
`● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-11-20 06:24:55 UTC; 22min ago
  Process: 17276 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 17300 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 17433 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 17436 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 17439 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 17459 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 17478 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 17496 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 17517 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=1/FAILURE)
  Process: 17523 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 17529 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 17535 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 17607 (docker-compose)
    Tasks: 34 (limit: 4915)
   Memory: 42.8M
   CGroup: /system.slice/tpot.service
           └─17607 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Loading plugin logjson v1.1.0
Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Servers will run as user honeytrap (2000).
Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Servers will run as group honeytrap (2000).
Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Loading default responses.
Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Connections will be handled in normal mode by default.
Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Logging to /opt/honeytrap/var/log/honeytrap.log.
Nov 20 06:47:01 magnificentshark docker-compose[17607]: honeytrap              |   Core module initialized.
Nov 20 06:47:04 magnificentshark docker-compose[17607]: logstash               | [2021-11-20T06:47:04,186][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http:
Nov 20 06:47:06 magnificentshark docker-compose[17607]: kibana                 | {"type":"log","@timestamp":"2021-11-20T06:47:06+00:00","tags":["warning","plugins","licensing"],"pid":20,"message":"License information could not be obtaine
Nov 20 06:47:06 magnificentshark docker-compose[17607]: kibana                 | {"type":"log","@timestamp":"2021-11-20T06:47:06+00:00","tags":["warning","plugins","licensing"],"pid":20,"message":"License information could not be obtaine
lines 1-31/31 (END)
`

**Comment by xirtam2669** [comment]
I am also having this issue ^

**Comment by rahulpawar1209** [comment]
I am facing the same issue ???
anyone solved ???
